#!/bin/bash
# Install CEMS hooks to ~/.claude/hooks/
# Run from repo root: ./hooks/install.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="$HOME/.claude/hooks"
CEMS_DIR="$HOME/.cems"
CREDS_FILE="$CEMS_DIR/credentials"

# --- Credentials setup ---
mkdir -p "$CEMS_DIR"

if [ ! -f "$CREDS_FILE" ]; then
    echo ""
    echo "=== CEMS Credentials Setup ==="
    echo "No credentials found at $CREDS_FILE"
    echo ""

    # API URL (with default)
    read -rp "CEMS API URL [https://cems.chocksy.com]: " INPUT_URL
    API_URL="${INPUT_URL:-https://cems.chocksy.com}"

    # API Key (required)
    while true; do
        read -rp "CEMS API Key: " INPUT_KEY
        if [ -n "$INPUT_KEY" ]; then
            break
        fi
        echo "  API key is required. Ask your team lead for a key."
    done

    cat > "$CREDS_FILE" <<EOF
# CEMS credentials — generated by install.sh
CEMS_API_URL=$API_URL
CEMS_API_KEY=$INPUT_KEY
EOF
    chmod 600 "$CREDS_FILE"
    echo "  Saved credentials to $CREDS_FILE (mode 600)"
    echo ""
else
    echo "Credentials found at $CREDS_FILE (skipping setup)"
fi

# --- Hook installation ---
mkdir -p "$TARGET_DIR/utils"

echo "Installing CEMS hooks to $TARGET_DIR..."

# Copy hook scripts
for f in cems_session_start.py user_prompts_submit.py cems_post_tool_use.py stop.py pre_tool_use.py pre_compact.py; do
    cp "$SCRIPT_DIR/$f" "$TARGET_DIR/$f"
    chmod +x "$TARGET_DIR/$f"
    echo "  Installed $f"
done

# Copy utils
for f in constants.py transcript.py hook_logger.py observer_manager.py credentials.py; do
    cp "$SCRIPT_DIR/utils/$f" "$TARGET_DIR/utils/$f"
    echo "  Installed utils/$f"
done

echo ""
echo "Done. All hooks installed."
echo ""
echo "The observer daemon will auto-start on your next Claude session."
echo "Credentials: $CREDS_FILE"
echo "Hooks: $TARGET_DIR"
