"""Setup command for CEMS CLI.

Installs hooks, skills, and credentials for Claude Code and/or Cursor.
All files are bundled inside the cems package — no clone needed.

Usage:
    cems setup              # Interactive (prompts for IDE + credentials)
    cems setup --claude     # Claude Code only, no prompts for IDE choice
    cems setup --cursor     # Cursor only
    cems setup --claude --api-url URL --api-key KEY   # Non-interactive
"""

import json
import shutil
import stat
import sys
from importlib import resources
from pathlib import Path

import click
from rich.table import Table

from cems.cli_utils import console


def _get_data_path() -> Path:
    """Get the path to bundled package data."""
    return Path(str(resources.files("cems.data")))


def _read_credentials() -> dict[str, str]:
    """Read ~/.cems/credentials as key=value pairs."""
    creds_file = Path.home() / ".cems" / "credentials"
    result = {}
    try:
        if creds_file.exists():
            for line in creds_file.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, _, value = line.partition("=")
                    result[key.strip()] = value.strip().strip("'\"")
    except OSError:
        pass
    return result


def _is_interactive() -> bool:
    """Check if stdin is a terminal (not piped)."""
    return sys.stdin.isatty()


def _setup_credentials(api_url: str | None = None, api_key: str | None = None) -> bool:
    """Ensure ~/.cems/credentials exists.

    If api_url/api_key are provided, use them directly (non-interactive).
    Otherwise prompt interactively if stdin is a TTY.

    Returns True if credentials are available.
    """
    cems_dir = Path.home() / ".cems"
    creds_file = cems_dir / "credentials"

    # Already configured
    if creds_file.exists() and not api_key:
        console.print(f"[green]Credentials:[/green] {creds_file}")
        return True

    # Non-interactive with explicit values
    if api_key:
        url = api_url or "https://cems.chocksy.com"
        cems_dir.mkdir(parents=True, exist_ok=True)
        creds_file.write_text(
            f"# CEMS credentials — generated by cems setup\n"
            f"CEMS_API_URL={url}\n"
            f"CEMS_API_KEY={api_key}\n"
        )
        creds_file.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
        console.print(f"[green]Saved credentials to {creds_file}[/green]")
        return True

    # Non-interactive without values — can't prompt
    if not _is_interactive():
        console.print("[yellow]No credentials found and stdin is not a terminal.[/yellow]")
        console.print()
        console.print("Configure credentials with one of:")
        console.print("  cems setup --claude --api-url URL --api-key KEY")
        console.print("  Or create ~/.cems/credentials manually:")
        console.print("    CEMS_API_URL=https://cems.chocksy.com")
        console.print("    CEMS_API_KEY=your-key-here")
        return False

    # Interactive prompt
    console.print()
    console.print("[bold]Credentials Setup[/bold]")
    console.print("No credentials found. Get these from your CEMS admin.")
    console.print()

    api_url = click.prompt(
        "CEMS API URL",
        default="https://cems.chocksy.com",
        show_default=True,
    )
    api_key = click.prompt("CEMS API Key", hide_input=True)

    if not api_key:
        console.print("[red]API key is required.[/red]")
        return False

    cems_dir.mkdir(parents=True, exist_ok=True)
    creds_file.write_text(
        f"# CEMS credentials — generated by cems setup\n"
        f"CEMS_API_URL={api_url}\n"
        f"CEMS_API_KEY={api_key}\n"
    )
    creds_file.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    console.print(f"[green]Saved credentials to {creds_file} (mode 600)[/green]")
    return True


def _install_claude_hooks(data_path: Path, api_url: str) -> None:
    """Install Claude Code hooks, skills, settings, and MCP config."""
    claude_dir = Path.home() / ".claude"
    hooks_dir = claude_dir / "hooks"
    skills_dir = claude_dir / "skills" / "cems"
    src_hooks = data_path / "claude" / "hooks"
    src_skills = data_path / "claude" / "skills" / "cems"

    # Copy hooks
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / "utils").mkdir(exist_ok=True)

    # Remove old-named hook files from previous installs
    for old_name in ["user_prompts_submit.py", "stop.py", "pre_tool_use.py", "pre_compact.py"]:
        old_file = hooks_dir / old_name
        if old_file.exists():
            old_file.unlink()

    hook_files = [
        "cems_session_start.py", "cems_user_prompts_submit.py",
        "cems_post_tool_use.py", "cems_stop.py", "cems_pre_tool_use.py", "cems_pre_compact.py",
    ]
    for f in hook_files:
        src = src_hooks / f
        if src.exists():
            dst = hooks_dir / f
            shutil.copy2(src, dst)
            dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    util_files = [
        "constants.py", "credentials.py", "hook_logger.py",
        "observer_manager.py", "transcript.py",
    ]
    for f in util_files:
        src = src_hooks / "utils" / f
        if src.exists():
            shutil.copy2(src, hooks_dir / "utils" / f)

    console.print(f"  Hooks installed to {hooks_dir}")

    # Copy skills
    skills_dir.mkdir(parents=True, exist_ok=True)
    for f in src_skills.iterdir():
        if f.suffix == ".md":
            shutil.copy2(f, skills_dir / f.name)
    console.print(f"  Skills installed to {skills_dir}")

    # Merge settings.json
    _merge_settings(claude_dir, data_path / "claude" / "settings.json")

    # Register MCP server
    _register_mcp_server(api_url)


def _register_mcp_server(api_url: str) -> None:
    """Register CEMS MCP server in Claude Code config.

    Adds the CEMS MCP server to ~/.claude.json with Bearer token auth
    using ${CEMS_API_KEY} env var expansion.
    """
    claude_json = Path.home() / ".claude.json"

    existing: dict = {}
    if claude_json.exists():
        try:
            existing = json.loads(claude_json.read_text())
        except json.JSONDecodeError:
            existing = {}

    mcp_servers = existing.setdefault("mcpServers", {})

    # Build MCP URL from API URL (same host, /mcp path on port 8766)
    # e.g. https://cems.chocksy.com -> https://cems.chocksy.com/mcp
    mcp_url = api_url.rstrip("/") + "/mcp"

    mcp_servers["cems"] = {
        "type": "http",
        "url": mcp_url,
        "headers": {
            "Authorization": "Bearer ${CEMS_API_KEY}",
        },
    }

    claude_json.write_text(json.dumps(existing, indent=2) + "\n")
    console.print(f"  MCP server registered in {claude_json}")


def _migrate_old_hook_names(hooks: dict) -> None:
    """Remove old-named CEMS hooks from settings so they get replaced by new cems_ prefixed ones."""
    # Match only hooks under ~/.claude/hooks/ with old names (won't touch user hooks elsewhere)
    old_patterns = {
        ".claude/hooks/user_prompts_submit.py",
        ".claude/hooks/stop.py",
        ".claude/hooks/pre_tool_use.py",
        ".claude/hooks/pre_compact.py",
    }
    for event_name, entries in hooks.items():
        hooks[event_name] = [
            entry for entry in entries
            if not any(
                any(pattern in hook.get("command", "") for pattern in old_patterns)
                for hook in entry.get("hooks", [])
            )
        ]


def _merge_settings(claude_dir: Path, template_path: Path) -> None:
    """Merge CEMS hook config into existing ~/.claude/settings.json.

    Preserves all existing settings (env, permissions, non-CEMS hooks).
    Only adds/updates hook events that CEMS needs.
    """
    settings_file = claude_dir / "settings.json"

    # Load existing settings or start fresh
    existing: dict = {}
    if settings_file.exists():
        try:
            existing = json.loads(settings_file.read_text())
        except json.JSONDecodeError:
            existing = {}

    # Load CEMS hook template
    template = json.loads(template_path.read_text())
    cems_hooks = template.get("hooks", {})

    # Migrate old hook names → new cems_ prefix names
    existing_hooks = existing.setdefault("hooks", {})
    _migrate_old_hook_names(existing_hooks)

    # Merge hooks: for each hook event, add CEMS hooks if not already present
    for event_name, cems_entries in cems_hooks.items():
        if event_name not in existing_hooks:
            # No existing config for this event — add CEMS entries directly
            existing_hooks[event_name] = cems_entries
        else:
            # Event exists — check if CEMS hooks are already registered
            existing_commands = set()
            for entry in existing_hooks[event_name]:
                for hook in entry.get("hooks", []):
                    existing_commands.add(hook.get("command", ""))

            for cems_entry in cems_entries:
                for hook in cems_entry.get("hooks", []):
                    if hook.get("command", "") not in existing_commands:
                        # CEMS hook not present — add this entry
                        existing_hooks[event_name].append(cems_entry)
                        break

    settings_file.write_text(json.dumps(existing, indent=2) + "\n")
    console.print(f"  Settings merged into {settings_file}")


def _install_cursor_hooks(data_path: Path) -> None:
    """Install Cursor hooks."""
    cursor_dir = Path.home() / ".cursor"
    hooks_dir = cursor_dir / "hooks"
    src_hooks = data_path / "cursor" / "hooks"
    src_hooks_json = data_path / "cursor" / "hooks.json"

    cursor_dir.mkdir(parents=True, exist_ok=True)
    hooks_dir.mkdir(exist_ok=True)

    # Copy hook scripts
    for f in src_hooks.iterdir():
        if f.suffix == ".py":
            dst = hooks_dir / f.name
            shutil.copy2(f, dst)
            dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    # Handle hooks.json
    hooks_json = cursor_dir / "hooks.json"
    if hooks_json.exists():
        console.print(f"  [yellow]Existing hooks.json found — you may need to merge manually[/yellow]")
    else:
        shutil.copy2(src_hooks_json, hooks_json)

    console.print(f"  Cursor hooks installed to {hooks_dir}")


@click.command()
@click.option("--claude", "install_claude", is_flag=True, help="Install Claude Code hooks only")
@click.option("--cursor", "install_cursor", is_flag=True, help="Install Cursor hooks only")
@click.option("--api-url", help="CEMS server URL (non-interactive)")
@click.option("--api-key", help="CEMS API key (non-interactive)")
def setup(install_claude: bool, install_cursor: bool, api_url: str | None, api_key: str | None) -> None:
    """Set up CEMS hooks and credentials for your IDE.

    Installs hooks, skills, and settings for Claude Code and/or Cursor.
    Prompts for API credentials if not already configured.

    \b
    Examples:
        cems setup              # Interactive
        cems setup --claude     # Claude Code only
        cems setup --cursor     # Cursor only
        cems setup --claude --api-url URL --api-key KEY  # Non-interactive
    """
    console.print()
    console.print("[bold]CEMS Setup[/bold]")
    console.print()

    data_path = _get_data_path()

    # Determine what to install
    if not install_claude and not install_cursor:
        if _is_interactive():
            # Interactive mode — ask
            console.print("Which IDE(s) to configure?")
            console.print("  1) Claude Code")
            console.print("  2) Cursor")
            console.print("  3) Both")
            console.print()
            choice = click.prompt("Choose", type=click.IntRange(1, 3), default=1)
            install_claude = choice in (1, 3)
            install_cursor = choice in (2, 3)
        else:
            # Non-interactive — default to Claude Code
            console.print("[yellow]Non-interactive mode: installing Claude Code hooks (use --cursor for Cursor)[/yellow]")
            install_claude = True

    # Credentials
    if not _setup_credentials(api_url=api_url, api_key=api_key):
        raise click.Abort()

    console.print()

    # Resolve API URL for MCP registration
    creds = _read_credentials()
    resolved_url = api_url or creds.get("CEMS_API_URL", "https://cems.chocksy.com")

    # Install
    if install_claude:
        console.print("[bold blue]Claude Code[/bold blue]")
        _install_claude_hooks(data_path, resolved_url)
        console.print()

    if install_cursor:
        console.print("[bold blue]Cursor[/bold blue]")
        _install_cursor_hooks(data_path)
        console.print()

    # Summary
    console.print("[bold green]Setup complete![/bold green]")
    console.print()

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="cyan")
    table.add_column(style="white")
    table.add_row("Credentials", str(Path.home() / ".cems" / "credentials"))
    if install_claude:
        table.add_row("Claude hooks", str(Path.home() / ".claude" / "hooks"))
        table.add_row("Claude skills", str(Path.home() / ".claude" / "skills" / "cems"))
        table.add_row("MCP server", str(Path.home() / ".claude.json"))
    if install_cursor:
        table.add_row("Cursor hooks", str(Path.home() / ".cursor" / "hooks"))
    console.print(table)

    console.print()
    console.print("[bold]Add to your shell profile (~/.zshrc or ~/.bashrc):[/bold]")
    console.print()
    console.print('  [cyan]eval "$(cems env)"[/cyan]')
    console.print()
    console.print("This exports CEMS_API_KEY so the MCP server can authenticate.")
    console.print("Then restart your shell and IDE.")
    console.print()
    console.print("Test: [cyan]cems health[/cyan]")
