"""Setup command for CEMS CLI.

Installs hooks, skills, and credentials for Claude Code and/or Cursor.
All files are bundled inside the cems package — no clone needed.

Usage:
    cems setup              # Interactive (prompts for IDE + credentials)
    cems setup --claude     # Claude Code only, no prompts for IDE choice
    cems setup --cursor     # Cursor only
"""

import json
import shutil
import stat
from importlib import resources
from pathlib import Path

import click
from rich.table import Table

from cems.cli_utils import console


def _get_data_path() -> Path:
    """Get the path to bundled package data."""
    return Path(str(resources.files("cems.data")))


def _setup_credentials() -> bool:
    """Ensure ~/.cems/credentials exists. Prompt if missing.

    Returns True if credentials are available.
    """
    cems_dir = Path.home() / ".cems"
    creds_file = cems_dir / "credentials"

    if creds_file.exists():
        console.print(f"[green]Credentials:[/green] {creds_file}")
        return True

    console.print()
    console.print("[bold]Credentials Setup[/bold]")
    console.print("No credentials found. Get these from your CEMS admin.")
    console.print()

    api_url = click.prompt(
        "CEMS API URL",
        default="https://cems.chocksy.com",
        show_default=True,
    )
    api_key = click.prompt("CEMS API Key", hide_input=False)

    if not api_key:
        console.print("[red]API key is required.[/red]")
        return False

    cems_dir.mkdir(parents=True, exist_ok=True)
    creds_file.write_text(
        f"# CEMS credentials — generated by cems setup\n"
        f"CEMS_API_URL={api_url}\n"
        f"CEMS_API_KEY={api_key}\n"
    )
    creds_file.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    console.print(f"[green]Saved credentials to {creds_file} (mode 600)[/green]")
    return True


def _install_claude_hooks(data_path: Path) -> None:
    """Install Claude Code hooks, skills, and settings."""
    claude_dir = Path.home() / ".claude"
    hooks_dir = claude_dir / "hooks"
    skills_dir = claude_dir / "skills" / "cems"
    src_hooks = data_path / "claude" / "hooks"
    src_skills = data_path / "claude" / "skills" / "cems"

    # Copy hooks
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / "utils").mkdir(exist_ok=True)

    hook_files = [
        "cems_session_start.py", "user_prompts_submit.py",
        "cems_post_tool_use.py", "stop.py", "pre_tool_use.py", "pre_compact.py",
    ]
    for f in hook_files:
        src = src_hooks / f
        if src.exists():
            dst = hooks_dir / f
            shutil.copy2(src, dst)
            dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    util_files = [
        "constants.py", "credentials.py", "hook_logger.py",
        "observer_manager.py", "transcript.py",
    ]
    for f in util_files:
        src = src_hooks / "utils" / f
        if src.exists():
            shutil.copy2(src, hooks_dir / "utils" / f)

    console.print(f"  Hooks installed to {hooks_dir}")

    # Copy skills
    skills_dir.mkdir(parents=True, exist_ok=True)
    for f in src_skills.iterdir():
        if f.suffix == ".md":
            shutil.copy2(f, skills_dir / f.name)
    console.print(f"  Skills installed to {skills_dir}")

    # Merge settings.json
    _merge_settings(claude_dir, data_path / "claude" / "settings.json")


def _merge_settings(claude_dir: Path, template_path: Path) -> None:
    """Merge CEMS hook config into existing ~/.claude/settings.json.

    Preserves all existing settings (env, permissions, non-CEMS hooks).
    Only adds/updates hook events that CEMS needs.
    """
    settings_file = claude_dir / "settings.json"

    # Load existing settings or start fresh
    existing: dict = {}
    if settings_file.exists():
        try:
            existing = json.loads(settings_file.read_text())
        except json.JSONDecodeError:
            existing = {}

    # Load CEMS hook template
    template = json.loads(template_path.read_text())
    cems_hooks = template.get("hooks", {})

    # Merge hooks: for each hook event, add CEMS hooks if not already present
    existing_hooks = existing.setdefault("hooks", {})

    for event_name, cems_entries in cems_hooks.items():
        if event_name not in existing_hooks:
            # No existing config for this event — add CEMS entries directly
            existing_hooks[event_name] = cems_entries
        else:
            # Event exists — check if CEMS hooks are already registered
            existing_commands = set()
            for entry in existing_hooks[event_name]:
                for hook in entry.get("hooks", []):
                    existing_commands.add(hook.get("command", ""))

            for cems_entry in cems_entries:
                for hook in cems_entry.get("hooks", []):
                    if hook.get("command", "") not in existing_commands:
                        # CEMS hook not present — add this entry
                        existing_hooks[event_name].append(cems_entry)
                        break

    settings_file.write_text(json.dumps(existing, indent=2) + "\n")
    console.print(f"  Settings merged into {settings_file}")


def _install_cursor_hooks(data_path: Path) -> None:
    """Install Cursor hooks."""
    cursor_dir = Path.home() / ".cursor"
    hooks_dir = cursor_dir / "hooks"
    src_hooks = data_path / "cursor" / "hooks"
    src_hooks_json = data_path / "cursor" / "hooks.json"

    cursor_dir.mkdir(parents=True, exist_ok=True)
    hooks_dir.mkdir(exist_ok=True)

    # Copy hook scripts
    for f in src_hooks.iterdir():
        if f.suffix == ".py":
            shutil.copy2(f, hooks_dir / f.name)

    # Handle hooks.json
    hooks_json = cursor_dir / "hooks.json"
    if hooks_json.exists():
        console.print(f"  [yellow]Existing hooks.json found — you may need to merge manually[/yellow]")
    else:
        shutil.copy2(src_hooks_json, hooks_json)

    console.print(f"  Cursor hooks installed to {hooks_dir}")


@click.command()
@click.option("--claude", "install_claude", is_flag=True, help="Install Claude Code hooks only")
@click.option("--cursor", "install_cursor", is_flag=True, help="Install Cursor hooks only")
def setup(install_claude: bool, install_cursor: bool) -> None:
    """Set up CEMS hooks and credentials for your IDE.

    Installs hooks, skills, and settings for Claude Code and/or Cursor.
    Prompts for API credentials if not already configured.

    \b
    Examples:
        cems setup              # Interactive
        cems setup --claude     # Claude Code only
        cems setup --cursor     # Cursor only
    """
    console.print()
    console.print("[bold]CEMS Setup[/bold]")
    console.print()

    data_path = _get_data_path()

    # Determine what to install
    if not install_claude and not install_cursor:
        # Interactive mode
        console.print("Which IDE(s) to configure?")
        console.print("  1) Claude Code")
        console.print("  2) Cursor")
        console.print("  3) Both")
        console.print()
        choice = click.prompt("Choose", type=click.IntRange(1, 3), default=1)
        install_claude = choice in (1, 3)
        install_cursor = choice in (2, 3)

    # Credentials
    if not _setup_credentials():
        raise click.Abort()

    console.print()

    # Install
    if install_claude:
        console.print("[bold blue]Claude Code[/bold blue]")
        _install_claude_hooks(data_path)
        console.print()

    if install_cursor:
        console.print("[bold blue]Cursor[/bold blue]")
        _install_cursor_hooks(data_path)
        console.print()

    # Summary
    console.print("[bold green]Setup complete![/bold green]")
    console.print()

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="cyan")
    table.add_column(style="white")
    table.add_row("Credentials", str(Path.home() / ".cems" / "credentials"))
    if install_claude:
        table.add_row("Claude hooks", str(Path.home() / ".claude" / "hooks"))
        table.add_row("Claude skills", str(Path.home() / ".claude" / "skills" / "cems"))
    if install_cursor:
        table.add_row("Cursor hooks", str(Path.home() / ".cursor" / "hooks"))
    console.print(table)

    console.print()
    console.print("Next: restart your IDE. The observer daemon will auto-start.")
    console.print("Test: [cyan]cems health[/cyan]")
